### ISSUE TITLE
Different Results: Disk Status vs iPhone Settings

### ISSUE THREAD

**Issue by aliimran** [thanhcuong1990/swift-disk-status#1]
Hello, 

I have tested it on two devices, and found out that Disk Status results are different from iPhone Storage results shown in iPhone Settings.

Device 1: iPhone 6 16gb, iOS 11.2.1 
Settings >  General > iPhone Storage: 8.2gb of 16gb used
swift-disk-status: Free Disk Space 5.99 GB

Device 2: iPhone 6 64gb, iOS 11.2.1 
Settings >  General > iPhone Storage: 37.1 GB of 64 GB used
swift-disk-status: Free Disk Space 12.33 GB

I haven't been able to figure out the reason.  Any help from your end would be great.

Thanks!

Ali

**Comment by simonpac** [comment]
Were you able to figure this out @aliimran I am also facing the same issue.

**Comment by aliimran** [comment]
@simonpac I guess it is some issue from apple's end. Try comparing your iPhone remaining storage from iTunes and Xcode -> Window -> Devices and Simulators. You will see different results.

**Comment by simonpac** [comment]
Thank you @aliimran I saw that iTunes was different as well...

**Comment by simonpac** [comment]
@aliimran 

Check these links out:

https://stackoverflow.com/a/47463829/511287

https://developer.apple.com/documentation/foundation/urlresourcekey/checking_volume_storage_capacity

This is apparently new to iOS 11 and can be solved...

**Comment by aliimran** [comment]
@simonpac Thanks (y)

**Comment by thanhcuong1990** [comment]
Fixed https://github.com/thanhcuong1990/swift-disk-status/tree/5d0b183175f1cbdf2ce68ee0f01a11228da49a69
